import {
  Brush,
  Delete,
  DraftingCompass,
  DraftingCompassIcon,
  Home,
  Link,
  Link2,
  FolderOpenDot,
  ClipboardSignature,
  Loader,
  Menu,
  Moon,
  Pen,
  Plus,
  PlusCircle,
  BookHeart,
  Settings,
  Sun,
  Users,
} from "lucide-react";

export const Icons = {
  home: Home,
  users: Users,
  settings: Settings,
  sun: Sun,
  moon: Moon,
  spinner: Loader,
  menu: Menu,
  link: Link,
  link2: Link2,
  plus: PlusCircle,
  draw: Pen,
  brush: Brush,
  drafting: DraftingCompass,
  drafting2: DraftingCompassIcon,
  delete: Delete,
  clip: ClipboardSignature,
  folder: FolderOpenDot,
  mine: BookHeart,
};
